### PR TITLE
use lenspath library to simplify replica maps wrapping/unwrapping

### PR DESCRIPTION
**Pull request by sudeepdino008**

### CODE REVIEW

**Comment by sudeepdino008** [comment]
move lenspath to covalenthq/

**Review by noslav — CHANGES_REQUESTED** [review]
This PR is failing for my local test -  

```go
go run ./extractor2.go --binary-file-path="../../bin/0.35/" --codec-path "../../codec/block-ethereum.avsc" --indent-json 0 --end-block-number 17090970 --start-block-number 17090930 --chain-id "1"
# github.com/covalenthq/bsp-agent/internal/utils
../../internal/utils/lenspath.go:34:1: missing return
../../internal/utils/lenspath.go:45:1: missing return
```

here's a link to the files I'm using it on - https://github.com/covalenthq/rudder/tree/main/test-data/codec-0.35/encoded

Please add a fix and test `lenspath` with those files?

**Comment by noslav** [comment]
Also, the `lenspath` path needs to be updated across the repo from - 	`github.com/sudeepdino008/lenspath` to `github.com/covalenthq/lenspath` 

```go
github.com/covalenthq/lenspath: github.com/covalenthq/lenspath@v0.3.1: parsing go.mod:
	module declares its path as: github.com/sudeepdino008/lenspath
	        but was required as: github.com/covalenthq/lenspath
```

**Comment by sudeepdino008** [comment]
@noslav ack. Please check now.

**Review by noslav — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
