### PR TITLE
script to convert avro encoded replicas into specimen and result jsons

### PR DESCRIPTION
**Pull request by fatemebagherii**

### CODE REVIEW

**Review by sudeepdino008 — APPROVED** [review]

**Comment by noslav** [comment]
@fatemebagherii why was the `codec/codegen.go` removed?

**Comment by fatemebagherii** [comment]
> @fatemebagherii why was the `codec/codegen.go` removed?

Seems like it's been removed in this [commit](https://github.com/covalenthq/bsp-agent/commit/36c9bb4a906830f7d3f995df30cbfb91c07b4961). I can't think of any reason for it. Maybe @sudeepdino008 can give us some insight?

**Comment by sudeepdino008** [comment]
I realized it got deleted, but it didn't seem to be used anywhere and so just kept it like that. @noslav

**Review by noslav — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
